config/routes.rb
Colchonet::Application.routes.draw do
  resources :rooms
  resources :users

  resource :confirmation, :only => [:show]
  resource :user_sessions, :only => [:create, :new, :destroy]

  root :to => "home#index"

  

end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  scope :most_recent, order('created_at DESC')

  def complete_name
    "#{title}, #{location}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rooms
  
  before_create :generate_token

  scope :confirmed, where('confirmed_at IS NOT NULL')

	validates_presence_of :email, :full_name, :location
	validates_length_of :bio, :minimum => 30, :allow_blank => false
	validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
	validates_uniqueness_of :email

  has_secure_password

  def generate_token
    self.confirmation_token = SecureRandom.urlsafe_base64
  end

  def confirm!
    return if confirmed?

    self.confirmed_at = Time.current
    self.confirmation_token = ''
    save!
  end

  def confirmed?
    confirmed_at.present?
  end

  def self.authenticate(email, password)
    confirmed.
      find_by(email: email).
      try(:authenticate, password)
  end

end

app/models/user_session.rb
class UserSession

  include ActiveModel::Validations
  include ActiveModel::Conversion

  extend ActiveModel::Naming
  extend ActiveModel::Translation

  attr_accessor :email, :password

  validates_presence_of :email, :password

  def initialize(session, attributes={})
    @session = session
    @email = attributes[:email]
    @password = attributes[:password]
  end


  def persisted?
    false
  end

  def authenticate
    user = User.authenticate(@email, @password)

    if user.present?
      store(user)
    else
      errors.add(:base, 'Login invalido')
      false
    end
  end

  def store(user)
    @session[:user_id] = user.id
  end

  def current_user
    User.find(@session[:user_id])
  end

  def user_signed_in?
    @session[:user_id].present?
  end

  def destroy
    @session[:user_id] = nil
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  delegate :current_user, :user_signed_in?, :to => :user_session
  helper_method :current_user, :user_signed_in?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def user_session
    UserSession.new(session)
  end

  def require_authentication
    unless user_signed_in?
      redirect_to new_user_sessions_path,
        :alert => "É necessário realizar o Login"
    end
  end
  
  def require_no_authentication
    redirect_to root_path if user_signed_in?
  end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController

  def show
    user = User.find_by_confirmation_token(params[:token])

    if user.present?
      user.confirm!
      redirect_to user, :notice => 'Usuario confirmado com sucesso!'
    else
      redirect_to root_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @rooms = Room.limit(3)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_filter :require_authentication, :only => [:new, :edit, :create, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.most_recent
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])
  end

  # GET /rooms/new
  def new
    @room = current_user.rooms.build
  end

  # GET /rooms/1/edit
  def edit
    @room = current_user.rooms.build(parms[:room])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = current_user.rooms.build(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render action: 'show', status: :created, location: @room }
      else
        format.html { render action: 'new' }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    @room = current_user.rooms.find(params[:id])

    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = current_user.rooms.find(params[:id])
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :location, :description)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
    @session = UserSession.new(session)
  end

  def create
    @session = UserSession.new(session, params[:user_session])
    if @session.authenticate
      redirect_to root_path, :notice => 'Logado'
    else
      render :new
    end
  end

  def destroy
    user_session.destroy
    redirect_to root_path, :notice => 'Deslogado com sucesso!'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_authentication, :only => [:new, :create]
  before_filter :can_change, :only => [:edit, :update]

  def new
    @user = User.new    
  end

  def create
    @user = User.create(create_params)
    if @user.save
      SignupMailer.confirm_email(@user).deliver
      redirect_to @user, :notice => 'Cadastro criado com sucesso!'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(create_params)
      redirect_to @user, :notice => 'Cadastro atualizado com sucesso!'
    else
      render :edit
    end
  end

  def index
    @users = User.all
  end

  private

    def create_params
      params.require(:user).permit(:email, :full_name, :bio, :location,
        :password, :password_confirmation)
    end

    def can_change
      unless user_signed_in? && current_user == user
        redirect_to user_path(params[:id])
      end
    end

    def user
      @user ||= User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag :div, model.errors[attribute].first,
        :class => 'error_message'
    end
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper

  def belongs_to_user(room)
    user_signed_in? && room.user == current_user
  end

end

app/views/home/index.html.erb
<h1>Quartos recém postados</h1>

<ul>
  <% @rooms.each do |room| %>
    <li><%= link_to room.complete_name, room %> </li>
  <% end %>
</ul>

app/views/layouts/_user_navbar.html.erb
<nav>
  <ul>
    <li>
    <%= link_to "Novo Quarto", new_room_path %> </li>
    <li>
    <%= link_to "Quartos", rooms_path %>
    </li>
    <li>
    <%= link_to "Meu Profile", user_path(current_user) %>
    </li>
    <li>
    <%= link_to "Logout", user_sessions_path, :method => :delete %>
    </li>
  </ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to "Quartos", rooms_path %> </li>
    <li><%= link_to "Cadastro", new_user_path %> </li>
    <li><%= link_to "Login", new_user_sessions_path %> </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colchonet</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div id="header-wrap">
      <h1><%= link_to "colchonet", root_path %></h1>
      <% if user_signed_in? %>
        <%= render 'layouts/user_navbar' %>
      <% else %>
        <%= render 'layouts/visitor_navbar' %>
      <% end %>
    </div>
  </header>
  <div id="content">
    <% if notice.present? %>
      <p id="notice"><%= notice %> </p>
    <% end %>
    <% if alert.present? %>
      <p id="alert"><%= alert %> </p>
    <% end %>
    
    <%= yield %>
  </div>
</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<article class="room">
  <h2><%= link_to room.title, room %> </h2>
  <span class="created">

  <%= 'Dono do quarto: ' + room.user.full_name %>
    
  </span>
  <p>
    <span class="location">
      <%= link_to room.location,"https://maps.google.com/?q=#{room.location}", :target => :blank %>
    </span>
  </p>
  <p><%= room.description %> </p>
  <% if belongs_to_user(room) %>
  <ul>
    <li><%= link_to 'Editar', edit_room_path(room) %></li>
    <li><%= link_to 'Deletar', room_path(room), 
      :method => :delete, :data => {:confirm => 'Deseja realmente deletar o quarto?'} %>
    </li>
  </ul>
  <% end %>
</article>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Listing rooms</h1>

<% @rooms.each do |room| %>
  <%= render room %>
<% end %>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @room.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @room.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/user_sessions/new.html.erb
<h1> Titulo </h1>

<% if @session.errors.has_key? :base %>
  <div id="error_explanation">
    <%= @session.errors[:base].join(', ') %>
  </div>
<% end %>

<%= form_for @session do |f| %> <p>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= error_tag @session, :email %> </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %> <%= error_tag @session, :password %>
  </p>

  <p><%= f.submit %></p>
<% end %>

<p><%= link_to 'Sign Up', new_user_path %> </p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      Há erros no formulário, por favor verifique.
    </div>
  <% end %>
  <p>
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
    <%= error_tag @user, :full_name %>
  </p>
  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
  <%= error_tag @user, :location %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= error_tag @user, :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= error_tag @user, :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= error_tag @user, :password_confirmation %>
  </p>
  <p>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
    <%= error_tag @user, :bio %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/users/edit.html.erb
<h1>Editando Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Lista de Usuário</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td></td>
        <td><%= link_to 'Exibir', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo usuário', new_user_path %>

app/views/users/new.html.erb
<h1>Cadastro de Usuário</h1>

<%= render 'form' %>

<%= link_to "Voltar", @user %>

app/views/users/show.html.erb
<h2>Perfil: <%= @user.full_name %></h2>

<ul>
  <li>Localização: <%= @user.location %></li>
  <li>Bio: <%= @user.bio %></li>
</ul>

<%= link_to 'Editar Perfil', edit_user_path(@user) %>
<%= link_to 'Home', root_path %>